### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FlyingndCoding** [moyaiu/moyaiu.github.io#1]
I think you should replace ditch with forgot
like coz it kind of sounds not so formal

**Comment by FlyingndCoding** [comment]
Also this page looks horrible can u do something:
https://moyaiu.github.io/news

**Comment by DaSussy** [comment]
never thought that someome actually visits the repo lmap

**Comment by DaSussy** [comment]
> Also this page looks horrible can u do something:
> 
> https://moyaiu.github.io/news

oh yeah i misspelled the css import lemme fix

**Comment by DaSussy** [comment]
> I think you should replace ditch with forgot
> 
> like coz it kind of sounds not so formal

 im changing that thing to another sentence soon🗿🤙

**Comment by FlyingndCoding** [comment]
Ok cool
